### PR TITLE
Add cell nib registration

### PR DESCRIPTION
**Pull request by oozywaters**
ANTableController now is able to register cells created via Interface Builder.

### CODE REVIEW

**Comment by oozywaters** [comment]
What is preferable way handle nil objects?

**Comment by oozywaters** [comment]
What is preferable way to handle nil objects?
`NSParameterAssert(templateCell)`?

**Comment by OlegPanfyorov** [comment]
in case if nil just do not add it. ParameterAssert will be disabled in case not DEBUG mode and app will crash.

**Comment by oozywaters** [comment]
Am I doing things right?
```
- (void)registerCellNib:(NSString *)nibName forModelClass:(Class)modelClass {
    UINib *nib = [UINib nibWithNibName:nibName bundle:nil];
    UITableViewCell *templateCell = [[nib instantiateWithOwner:nil options:nil] firstObject];
    Class cellClass = [templateCell class];

    ...

    if (cellClass && modelClass) {
        [self.cellMappingsDictionary setObject:[ANRuntimeHelper classStringForClass:cellClass]
                                        forKey:[ANRuntimeHelper modelStringForClass:modelClass]];
    }
}
```

**Comment by oks** [comment]
yep, thats fine

**Comment by oks** [comment]
pod update will be published in next 3 days, you can use it right now, adding ```:head``` to your podfile

**Pull request merged**
